### ISSUE TITLE
Express Server: unhandled error if port is already in use

### ISSUE THREAD

**Issue by cubadomingo** [tmobaird/i-want-to-contribute#83]
<img width="651" alt="screen shot 2017-08-16 at 12 54 23 pm" src="https://user-images.githubusercontent.com/15992549/29382670-2cd28c7c-8282-11e7-99d6-ef105eba38e1.png">

The server should have a backup port incase port 5000 is already in use. Currently it just throws this error and the `yarn start` command exits.

**Comment by tmobaird** [comment]
So I'm actually not sure this is fully possible. Both the client and server sides use port 5000 as a back up for where the server should be running (because the client needs to make requests to the server as well). It seems like it'd be really hard to make both the client and server automatically know which port the backend is running on, since they both run in different processes.

That being said, I'm open to suggestions.

**Comment by cubadomingo** [comment]
yeah I agree, you can disregard this.
